[project]
name = "helldivers-2-voice-stratagems"
version = "0.1.0"
description = "Send Helldivers 2 Stratagems Keypresses via voice commands recognized by Speech Recognition APIs"
authors = [{ name = "Alexey Rubaseff", email = "alexey.rubasheff@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "global-logger",
    "speechrecognition",
    "requests",
    "pyautogui",
    "pyaudio",
    "dynaconf[yaml]",
]

[project.scripts]
helldivers2_stratagem = "helldivers_2_voice_stratagems:main"

[build-system]
requires = ["uv_build>=0.11.17,<0.12"]
build-backend = "uv_build"
